[build]
  command = "rw deploy netlify"
  publish = "web/dist"
  functions = "api/dist/functions"

  [dev]
    # Note be sure to `netlify link` your site first
    command = "rw dev"
    framework = "#custom"
    targetPort = 8910 # The port for your application server, framework or site generator
    port = 8888 # The port that the netlify dev will be accessible on

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
