[build]
  command = "yarn rw deploy netlify"
  publish = "web/dist"
  functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"
  targetPort = 8910
  httpProxy = 8910
  port = 8888
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
